<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class JobListingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('job_listings')->insert([
            [
                'company_id' => 1,
                'job_category_id' => 1,
                'title' => 'Software Engineer',
                'slug' => Str::slug('Software Engineer'),
                'description' => 'Membangun aplikasi web menggunakan Laravel dan Vue.js.',
                'requirements' => 'Minimal 2 tahun pengalaman. Menguasai PHP, MySQL, dan JavaScript.',
                'responsibilities' => 'Mengembangkan fitur baru, maintenance sistem, serta kolaborasi dengan tim frontend.',
                'location' => 'Jakarta',
                'employment_type' => 'Full-time',
                'experience_level' => 'Mid-level',
                'education_level' => 'S1 Informatika',
                'salary_range' => '10-15jt',
                'vacancies' => 2,
                'deadline' => Carbon::now()->addDays(30),
                'is_active' => true,
                'is_featured' => true,
                'status' => 'open',
                'job_title' => 'Software Engineer',
                'job_field' => 'IT',
                'job_type' => 'Full-time',
                'work_system' => 'Hybrid',
                'location_country' => 'Indonesia',
                'location_address' => 'Jakarta Selatan',
                'job_description' => 'Bertanggung jawab dalam pengembangan aplikasi internal.',
                'salary_min' => 10000000,
                'salary_max' => 15000000,
                'bonus' => 'Asuransi kesehatan',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'company_id' => 2,
                'job_category_id' => 2,
                'title' => 'UI/UX Designer',
                'slug' => Str::slug('UI/UX Designer'),
                'description' => 'Mendesain antarmuka aplikasi yang user-friendly.',
                'requirements' => 'Menguasai Figma, Adobe XD, dan memiliki portfolio desain.',
                'responsibilities' => 'Membuat wireframe, prototype, serta berkolaborasi dengan developer.',
                'location' => 'Bandung',
                'employment_type' => 'Full-time',
                'experience_level' => 'Junior',
                'education_level' => 'S1 Desain',
                'salary_range' => '8-12jt',
                'vacancies' => 1,
                'deadline' => Carbon::now()->addDays(25),
                'is_active' => true,
                'is_featured' => false,
                'status' => 'open',
                'job_title' => 'UI/UX Designer',
                'job_field' => 'Design',
                'job_type' => 'Full-time',
                'work_system' => 'Remote',
                'location_country' => 'Indonesia',
                'location_address' => 'Bandung Kota',
                'job_description' => 'Mendesain aplikasi web dan mobile sesuai kebutuhan bisnis.',
                'salary_min' => 8000000,
                'salary_max' => 12000000,
                'bonus' => 'Transport allowance',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'company_id' => 3,
                'job_category_id' => 3,
                'title' => 'Digital Marketing Specialist',
                'slug' => Str::slug('Digital Marketing Specialist'),
                'description' => 'Meningkatkan branding perusahaan melalui media sosial dan iklan digital.',
                'requirements' => 'Menguasai SEO, Google Ads, dan Social Media Marketing.',
                'responsibilities' => 'Membuat strategi kampanye, analisis performa, dan laporan marketing.',
                'location' => 'Surabaya',
                'employment_type' => 'Contract',
                'experience_level' => 'Mid-level',
                'education_level' => 'S1 Marketing',
                'salary_range' => '7-10jt',
                'vacancies' => 1,
                'deadline' => Carbon::now()->addDays(20),
                'is_active' => true,
                'is_featured' => true,
                'status' => 'open',
                'job_title' => 'Digital Marketing Specialist',
                'job_field' => 'Marketing',
                'job_type' => 'Contract',
                'work_system' => 'Onsite',
                'location_country' => 'Indonesia',
                'location_address' => 'Surabaya Pusat',
                'job_description' => 'Membuat dan menjalankan kampanye digital marketing.',
                'salary_min' => 7000000,
                'salary_max' => 10000000,
                'bonus' => 'Performance bonus',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'company_id' => 4,
                'job_category_id' => 4,
                'title' => 'Data Analyst',
                'slug' => Str::slug('Data Analyst'),
                'description' => 'Menganalisis data untuk mendukung pengambilan keputusan bisnis.',
                'requirements' => 'Menguasai SQL, Python, dan tools visualisasi data (Tableau/PowerBI).',
                'responsibilities' => 'Membuat laporan data, dashboard, serta analisis prediktif.',
                'location' => 'Yogyakarta',
                'employment_type' => 'Full-time',
                'experience_level' => 'Senior',
                'education_level' => 'S1 Statistik/Informatika',
                'salary_range' => '12-18jt',
                'vacancies' => 2,
                'deadline' => Carbon::now()->addDays(40),
                'is_active' => true,
                'is_featured' => false,
                'status' => 'open',
                'job_title' => 'Data Analyst',
                'job_field' => 'Data',
                'job_type' => 'Full-time',
                'work_system' => 'Hybrid',
                'location_country' => 'Indonesia',
                'location_address' => 'Yogyakarta Timur',
                'job_description' => 'Bertanggung jawab dalam analisis data bisnis perusahaan.',
                'salary_min' => 12000000,
                'salary_max' => 18000000,
                'bonus' => 'Kesehatan + THR',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'company_id' => 5,
                'job_category_id' => 5,
                'title' => 'HR Manager',
                'slug' => Str::slug('HR Manager'),
                'description' => 'Mengelola tim HR untuk mendukung perkembangan perusahaan.',
                'requirements' => 'Berpengalaman minimal 5 tahun di bidang HR.',
                'responsibilities' => 'Rekrutmen, pelatihan, dan pengembangan karyawan.',
                'location' => 'Medan',
                'employment_type' => 'Full-time',
                'experience_level' => 'Senior',
                'education_level' => 'S1 Psikologi/Manajemen SDM',
                'salary_range' => '15-20jt',
                'vacancies' => 1,
                'deadline' => Carbon::now()->addDays(15),
                'is_active' => true,
                'is_featured' => true,
                'status' => 'open',
                'job_title' => 'HR Manager',
                'job_field' => 'Human Resource',
                'job_type' => 'Full-time',
                'work_system' => 'Onsite',
                'location_country' => 'Indonesia',
                'location_address' => 'Medan Barat',
                'job_description' => 'Memimpin tim HR dan mengelola kebijakan karyawan.',
                'salary_min' => 15000000,
                'salary_max' => 20000000,
                'bonus' => 'Annual bonus',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
